### ISSUE TITLE
呼び出し側でエラーハンドリングしたい

### ISSUE THREAD

**Issue by hhatto** [yajamon/zaif-api-rust#50]
はじめまして。
zaif-api-rustよいですね。便利に使っています。

一つ提案というか、設計方針や今後の対応についての確認なのですが、
今APIをコールした場合、`reqwest`に紐づくエラー(主にはネットワーク系)が発生した場合に`panic`になってしまうのですが、呼び出し側で処理を継続するか選択したいので、`panic`にしないで欲しいという要望です。
（例えば[このあたり](https://github.com/yajamon/zaif-api-rust/blob/6591bb62f7c934f4846aa6bdc6a786168da7a171/src/public_api/mod.rs#L33)や[is_success()がfalseの場合にアサーションでpanicになる箇所](https://github.com/yajamon/zaif-api-rust/blob/6591bb62f7c934f4846aa6bdc6a786168da7a171/src/core/api.rs#L54)）

このあたりの対応予定等があれば教えていただきたいです。

ちなみに今は[フォークしたこちらのブランチ](https://github.com/yajamon/zaif-api-rust/compare/master...hhatto:lazy-fixes)で、エラーが発生した場合でも無理やり`Ok`を返して、`serde_json`のデコード処理でエラーにして、最終的に呼び出し側でエラー判定したりしています。
一時回避的なかなり怠惰な実装です;-)

**Comment by yajamon** [comment]
issueありがとうございます！

> reqwestに紐づくエラー(主にはネットワーク系)が発生した場合にpanicになってしまうのですが、
> 呼び出し側で処理を継続するか選択したいので、panicにしないで欲しいという要望です。
>
> このあたりの対応予定等があれば教えていただきたいです。

こちら、承知しました。
ぼんやりとですが、エラーハンドリングの方針としては下記のいずれかを実施したいと考えている、といったところです。

- struct zaif_api::Errorを用意して、それをResultに詰めて返却する
- enum zaif::Errorを用意して、それをResultに詰めて返却する

**Comment by yajamon** [comment]
@hhatto 
エラーハンドリングできるようにしてv0.5.0を公開しました 😃 
お試しください 👍

**Comment by hhatto** [comment]
ありがとうございます!!
使いやすくなりました 🆒
